### ISSUE TITLE
try to install webdc3

### ISSUE THREAD

**Issue by lp880** [EIDA/webdc3#33]
Hello i try to install webdc3 but aofter Javier tell me to run python update-metadata.py -l DEBUG --singlenode "http://geofon.gfz-potsdam.de/fdsnws/station/1" it work in folder data is created xml files.

I go on web interface but in console give me that errors: 
![image](https://user-images.githubusercontent.com/62878807/77896487-11035480-7281-11ea-9ca7-769d6d04ea4a.png)

What is the next step In the documentation nothing is written about these files as they are obtained

**Comment by andres-h** [comment]
Those are not static files, but entry points to the WSGI web service, eg.:

https://github.com/EIDA/webdc3/blob/fc42103fe502903eda19109bf429fde33bda4c54/wsgi/modules/metadata.py#L90

It seems you have a problem with WSGI installation, so either the web server is looking for static files instead of running the web service or (more likely in this case) there is an error loading WSGI modules.

WebDC has two major components -- one is Javascript, the other is WSGI web service providing the required metadata to Javascript. The latter is not working properly in your case.

At first try to open "loader", eg., http://eida.gfz-potsdam.de/webdc3/wsgi/loader. If this works, your WSGI is basically working.

Now try "metadata/networktypes", eg., http://eida.gfz-potsdam.de/webdc3/wsgi/metadata/networktypes. If you get "404 Not Found" (as expected from the above picture), there is probably an error loading the metadata.py module. Most likely the [SC3 modules](https://github.com/EIDA/webdc3/blob/fc42103fe502903eda19109bf429fde33bda4c54/wsgi/modules/metadata.py#L58) cannot be found.

Making the SC3 environment (PYTHONPATH, LD_LIBRARY_PATH) available to WSGI can be tricky and it depends on Linux distribution and web server. I haven't used Apache in a while, but our nginx/uwsgi example is [here](https://github.com/EIDA/webdc3/issues/19#issuecomment-515438096).

**Comment by lp880** [comment]
Thanks for reply Andres, but when i try to install i stuck on documentation. 

When I downloaded the files from github I didn't find
in wsgi the metadata folder, so I created it manually. But I don't think that's right. I can not find in the documentation how to.

What I have done so far is as follows:
I downloaded the files from git I uploaded them to the server, I put the wsgi module in apashe2, I modified the virtual host as it says in the documentation, I put SEISCOMP_ROOT / etc / webinterface.cfg. and here I stopped, I do not know what steps I am taking because the documentation is here.

Please can you tell me the steps that need to be taken to be a functional interface. Thank you.

**Comment by andres-h** [comment]
> When I downloaded the files from github I didn't find in wsgi the metadata folder, so I created it manually. But I don't think that's right. I can not find in the documentation how to.

The documentation does not mention the metadata folder, because it is virtual (implemented in the Python script) and should not be created by the user.

If you can access "loader", but not "metadata/networktypes", then most likely the environment variables (SEISCOMP_ROOT, LD_LIBRARY_PATH, PYTHONPATH) are not seen by the Python script. Another possibility is that the Apache user does not have access to ~/seiscomp3.

You should see an error message in Apache error log.

> I downloaded the files from git I uploaded them to the server, I put the wsgi module in apache2, I modified the virtual host as it says in the documentation, I put SEISCOMP_ROOT / etc / webinterface.cfg. and here I stopped, I do not know what steps I am taking because the documentation stop here.

If everything goes as expected, this should be all, I think.

**Comment by lp880** [comment]
> If you can access "loader", but not "metadata/networktypes", then most likely the environment variables (SEISCOMP_ROOT, LD_LIBRARY_PATH, PYTHONPATH) are not seen by the Python script. Another possibility is that the Apache user does not have access to ~/seiscomp3.
> 
I can't access the loader and is no file "loader" in wsgi folder

**Comment by andres-h** [comment]
> Do I have to manually create the loader file with similar:

No, "loader" is a [Python function](https://github.com/EIDA/webdc3/blob/fc42103fe502903eda19109bf429fde33bda4c54/wsgi/modules/core.py#L8) too.

See our (working) installation:

$ ls webdc3/wsgi
descriptions eida.py inventorycache.py inventorycache.pyc modules webdc3.conf.sample webdc3.wsgi webinterface.cfg.sample webinterface.py webinterface.pyc wsgicomm.py wsgicomm.pyc

If "loader" does not work, then you have a problem with WSGI in general. Do you have mod_wsgi (for Python 2) installed? Eg., on Ubuntu/Debian you'll need the libapache2-mod-wsgi package.

See if the Python scripts are executed at all and check Apache's error log.

**Comment by lp880** [comment]
this is the error log

Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.29 mod_python/3.3.1 Python/2.7.6 mod_wsgi/3.4 configured -- resuming normal operations

mod_wsgi (pid=24797): Target WSGI script '/var/www/et.infp.ro/wsgi/webdc3.wsgi' cannot be loaded as Python module., referer: http://et.infp.ro/error.html
mod_wsgi (pid=24797): Exception occurred processing WSGI script '/var/www/et.infp.ro/wsgi/webdc3.wsgi'., referer: http://et.infp.ro/error.html
Traceback (most recent call last):, referer: http://et.infp.ro/error.html
File "/var/www/et.infp.ro/wsgi/webdc3.wsgi", line 6, in <module>, referer: http://et.infp.ro/error.html
import webinterface, referer: http://et.infp.ro/error.html
File "/var/www/et.infp.ro/wsgi/webinterface.py", line 234, in <module>, referer: http://et.infp.ro/error.html
wi = WebInterface(__name__), referer: http://et.infp.ro/error.html
File "/var/www/et.infp.ro/wsgi/webinterface.py", line 96, in __init__, referer: http://et.infp.ro/error.html
self.ic = InventoryCache(inventory), referer: http://et.infp.ro/error.html
File "/var/www/et.infp.ro/wsgi/inventorycache.py", line 102, in __init__, referer: http://et.infp.ro/error.html
 self.update(), referer: http://et.infp.ro/error.html
File "/var/www/et.infp.ro/wsgi/inventorycache.py", line 154, in update, referer: http://et.infp.ro/error.html
with open(self.cachefile) as cache:, referer: http://et.infp.ro/error.html

and this is webdc3 file: `
import os
import sys	

sys.path.insert(0, '/var/www/et.infp.ro/wsgi/')

import webinterface

application = webinterface.application`

**Comment by andres-h** [comment]
> File "/var/www/et.infp.ro/wsgi/inventorycache.py", line 154, in update, referer: http://et.infp.ro/error.html
> with open(self.cachefile) as cache:, referer: http://et.infp.ro/error.html

Looks like the webserver user does not have permission to open the cache file.

**Comment by lp880** [comment]
yes, i will do that permission but this error : mod_wsgi (pid=24797): Target WSGI script '/var/www/et.infp.ro/wsgi/webdc3.wsgi' cannot be loaded as python module. ?

**Comment by andres-h** [comment]
The error is misleading. The script cannot be loaded because of exception when trying to open the file.

**Comment by lp880** [comment]
Thanks, i will give permission  and will see next.

**Comment by lp880** [comment]
Hello Andres, can we talk in privat ?
Email or wahttap ?
