### ISSUE TITLE
Update-metadata fails

### ISSUE THREAD

**Issue by jan-michalek** [EIDA/webdc3#35]
There is problem with updating metadata in WedDC3 from EIDA nodes (see error below). However, the reported routing service http://ws.icgc.cat/eidaws/routing/1/query is running fine. What the issue might be? Should the datacenter be added to some verified registry first? 

Run:
```
[sysop@eida data]$ python ./update-metadata.py -l INFO 
INFO:root:Getting routes from www.orfeus-eu.org
INFO:root:Adding routes from www.orfeus-eu.org
INFO:root:Adding routes from geofon.gfz-potsdam.de
INFO:root:Adding routes from eida.ethz.ch
INFO:root:Adding routes from ws.resif.fr
INFO:root:Adding routes from webservices.ingv.it
INFO:root:Adding routes from erde.geophysik.uni-muenchen.de
INFO:root:Adding routes from ws.icgc.cat
INFO:root:Adding routes from eida.gein.noa.gr
INFO:root:Adding routes from eida-sc3.infp.ro
INFO:root:Adding routes from eida-service.koeri.boun.edu.tr
INFO:root:Adding routes from eida.bgr.de
INFO:root:Adding routes from eida.geo.uib.no
```
Error:
```
Traceback (most recent call last):
  File "./update-metadata.py", line 771, in <module>
    main()
  File "./update-metadata.py", line 548, in main
    foutput=foutput)
  File "./update-metadata.py", line 450, in downloadInventory
    archive = url2archive(dc)
  File "./update-metadata.py", line 502, in url2archive
    raise Exception('Unknown data centre: %s' % o.hostname)
Exception: Unknown data centre: ws.icgc.cat
```

**Comment by jan-michalek** [comment]
Resolved in the latest version.
